openapi: "3.0.1"
info:
  title: "cars API"
  description: "do the same as bookings"
  version: "2025-04-27T21:22:39Z"
servers:
- url: "https://l3vsv1mdge.execute-api.eu-north-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "default"
paths:
  /bookings/{booking_id}:
    get:
      parameters:
      - name: "booking_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /cars/{car_id}:
    get:
      parameters:
      - name: "car_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /cars:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /bookings:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
