# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: currency_converter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'currency_converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63urrency_converter.proto\x12\x12\x63urrency_converter\"L\n\x0e\x43onvertRequest\x12\x15\n\rfrom_currency\x18\x01 \x01(\t\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\"!\n\x0f\x43onvertResponse\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\"\x1f\n\x1dGetAvailableCurrenciesRequest\"4\n\x1eGetAvailableCurrenciesResponse\x12\x12\n\ncurrencies\x18\x01 \x03(\t2\xed\x01\n\x11\x43urrencyConverter\x12T\n\x07\x43onvert\x12\".currency_converter.ConvertRequest\x1a#.currency_converter.ConvertResponse\"\x00\x12\x81\x01\n\x16GetAvailableCurrencies\x12\x31.currency_converter.GetAvailableCurrenciesRequest\x1a\x32.currency_converter.GetAvailableCurrenciesResponse\"\x00\x42+\n\x0fse.project.grpcB\x16\x43urrencyConverterProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency_converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017se.project.grpcB\026CurrencyConverterProtoP\001'
  _globals['_CONVERTREQUEST']._serialized_start=48
  _globals['_CONVERTREQUEST']._serialized_end=124
  _globals['_CONVERTRESPONSE']._serialized_start=126
  _globals['_CONVERTRESPONSE']._serialized_end=159
  _globals['_GETAVAILABLECURRENCIESREQUEST']._serialized_start=161
  _globals['_GETAVAILABLECURRENCIESREQUEST']._serialized_end=192
  _globals['_GETAVAILABLECURRENCIESRESPONSE']._serialized_start=194
  _globals['_GETAVAILABLECURRENCIESRESPONSE']._serialized_end=246
  _globals['_CURRENCYCONVERTER']._serialized_start=249
  _globals['_CURRENCYCONVERTER']._serialized_end=486
# @@protoc_insertion_point(module_scope)
